### PR TITLE
add generating files

### PR DESCRIPTION
**Pull request by vadim9999**
https://github.com/GroceriStar/fake-api/issues/102

### CODE REVIEW

**Comment by atherdon** [comment]
am i right - it generating files inside of this module, right?

**Comment by vadim9999** [comment]
yes. you can delete all from folder output and run script
npm run generate

**Comment by atherdon** [comment]
awesome!
1) can you delete old versions of our files from: https://github.com/GroceriStar/sd/tree/master/src/data/Favorites
https://github.com/GroceriStar/sd/tree/master/src/data/Items
https://github.com/GroceriStar/sd/tree/master/src/data/UserGrocery
2) update paths in generator for these 3 files (but keep old version with output too - i like it and we'll use it - just comment it)
3) add line to readme - with explanation about how to run generator

**Comment by vadim9999** [comment]
ok

**Pull request merged**
