### PR TITLE
added modules in utils.js

### PR DESCRIPTION
**Pull request by uniyalprashant9**
Added getList() and getListContent() modules in src/util.js

### CODE REVIEW

**Comment by uniyalprashant9** [comment]
@atherdon I compared both files and it does not seem to be the same.
Screenshot (20)

**Comment by uniyalprashant9** [comment]
splitObject.js merged with writeFile.js

**Comment by uniyalprashant9** [comment]
@atherdon Please check this commit

**Comment by atherdon** [comment]
tell me more details about this PR - because it's hard right now to
understand what was done - it will help me to approve your changes more
quickly

>

**Comment by uniyalprashant9** [comment]
@atherdon  I made 3 modules.
1.splitObject in writeFile.js :- splits gorcery.js(large) object into to single elements in json.
2.getList() in utils.js :- this gives a list of elements in that were splitted by splitObject module.
3.getListContent() in utils.js :- this gives the content of elements that were splitted by splitModule.

Once these changes get approved I will update readme.md to tell other team members about changes.

**Comment by atherdon** [comment]
all that methods works and you can confirm that nothing went broken from
previous codebase?

>

**Comment by uniyalprashant9** [comment]
Yes, all methods are working fine.
I have attached screenshots. 
Screenshot (23)
Screenshot (21)
Screenshot (22)

**Comment by atherdon** [comment]
ok, let's merge then.

**Pull request merged**
