### PR TITLE
Update files.js

### PR DESCRIPTION
**Pull request by elnur004**

### CODE REVIEW

**Comment by vadim9999** [comment]
@elnur004 than change import path files that you have adedd

**Comment by elnur004** [comment]
need to add json files?

**Comment by vadim9999** [comment]
@elnur004 no, just change import path in src/files.js because when you moved it in src/data/ need to change import path in src/files.js.

**Comment by elnur004** [comment]
need to change all other imports path?

**Comment by vadim9999** [comment]
@elnur004 yes change other files that you have added

**Pull request merged**
