### PR TITLE
replaced files with filesES5

### PR DESCRIPTION
**Pull request by Beni03**
## Proposed changes

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request.
If it fixes a bug or resolves a feature request, be sure to link to that issue.

## Types of changes

What types of changes does your code introduce to static food data?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] refactor
- [ ] documentation
- [ ] other

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

Are tests included?
- [ ] yes (*bugfixes and features will not be merged without tests*)
- [ ] no

Breaking Changes?
- [ ] yes (*breaking changes will not be merged unless absolutely necessary*)
- [ ] no

List any relevant issue numbers:

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by atherdon** [comment]
here is an error log: 
```
Error: Could not resolve './filesES5' from src/index.js
```

**Comment by Beni03** [comment]
Sry for taking long time. I was getiing familiar with fit and github.

Even before changing the file name to filesES5 inside sd/src, I am getting
this error.

**Comment by Beni03** [comment]
By mistake I deleted those two pull requests will.. will reopen it. 
Is there any way I can do that task from the beginning?

**Comment by atherdon** [comment]
not a problem - you can take as much time you need. yes, you just need to sync your fork with latest changes that team made. do you need help with sync? and tell me if i need to close this PR and you'll open a new one

**Comment by Beni03** [comment]
Yes, I would like to get some help to sync my fork with the latest changes. Also can you please delete PR#381 and # 382? I will create a new PR.

Thanks,
Benitha

**Comment by atherdon** [comment]
ok, sure. you'll need to do this: https://github.com/ChickenKyiv/awesome-git-article/blob/master/README.md#keeping-a-fork-up-to-date

closing that your PRs

**Comment by Beni03** [comment]
I updated my fork with the latest changes and still I am getting this
error. Some problem with the import function.

**Comment by atherdon** [comment]
can you show me screen of error. because i don't see what error you have

**Comment by Beni03** [comment]
Error screen attached.

**Comment by atherdon** [comment]
i wasn't uploaded. use github for image please

**Comment by Beni03** [comment]
Error screen

**Comment by atherdon** [comment]
i actually newer tried to run it as you trying. this module is not a nodejs server so index.js is not a point of starting script.

**Comment by atherdon** [comment]
this module, in order to be run - should be published at npm and then installed at some js server.
but similar to groceristar-fetch - we can have a `play.js` files where you can try some of your functions.
another good way to track your code is to create tests, that will help you to reduce number of bugs

Tell me if it helps.

This is actually why we're using PRs for code review - each new PR with code changes, made by our members go installed at virtual machine and run all tests. you can see that here: https://travis-ci.org/GroceriStar/sd/jobs/541030813

**Comment by Beni03** [comment]
Ok will look in to it.
Just for understanding, how did you get this message
here is an error log:

Error: Could not resolve './filesES5' from src/index.js
—

**Comment by atherdon** [comment]
I get if from Travis CI virtual machine build. similar link that i shared with you in my prev message. your build just was crashing, because when you change your prev file location - it was necessary to update connection at index.js as well

**Comment by Beni03** [comment]
OK.
I have created another pull request for a commit with two changes. Is that
what you mean?
 Updating connection at index.js means as I have changed the file name
inside src to filesES5, I also have to update it in index.js right?

**Comment by atherdon** [comment]
yes that changes was good - i merged them. what about other things? can you create a new PR and move changes that you've made here? because this current PR is outdated with our latest changes

**Comment by atherdon** [comment]
let me try to do this - i'll open this PR and if it will work without any of our changes - i'll merge it and we'll be able to move to the next task, OK?

**Comment by atherdon** [comment]
i got it - it was done. closing this PR

**Pull request closed without merging**
