### PR TITLE
Update users.test.js

### PR DESCRIPTION
**Pull request by Edebo**
issue #22,adding test for the schema of users json file

## Proposed changes

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request.
If it fixes a bug or resolves a feature request, be sure to link to that issue.

## Types of changes

What types of changes does your code introduce to static food data?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] refactor
- [ ] documentation
- [ ] other

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

Are tests included?
- [ ] yes (*bugfixes and features will not be merged without tests*)
- [ ] no

Breaking Changes?
- [ ] yes (*breaking changes will not be merged unless absolutely necessary*)
- [ ] no

List any relevant issue numbers:

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by atherdon** [comment]
Please check this error log:
```
users data files returns array › validates users json
    TypeError: expect(...).toMatchSchema is not a function
      18 |       required: ['name', 'email', 'password']
      19 |     }
    > 20 |     expect({ name: 'page', email: 'page@gmail.com', password: 'pagethesdwrapper' }).toMatchSchema(schema)
         |                                                                                     ^
      21 |   })
      22 | })
      23 | 
      at Object.toMatchSchema (tests/users.test.js:20:85)
```

**Comment by atherdon** [comment]
Ok, looks awesome and tests work. Can you handle my @TODO that i mention at this file. and i'll be able to merge this pull request

**Comment by Edebo** [comment]
> Ok, looks awesome and tests work. Can you handle my @todo that i mention at this file. and i'll be able to merge this pull request

i dont understand

**Comment by atherdon** [comment]
no problem.
check this
```
// @TODO you can move away this test and wrap it with another describe block
  it('validates users json', () => {
    const schema = {
      properties: {
        name: { type: 'string' },
        email: { type: 'string' },
        password: { type: 'string' },
      },
      required: ['name','email','password'],
    };
  expect({ name: 'page', email:'page@gmail.com', password:'pagethesdwrapper' }).toMatchSchema(schema);
});
```

that is my @TODO

**Pull request merged**
