### PR TITLE
nutritionAttributes test upgraded

### PR DESCRIPTION
**Pull request by amogh-jrules**
Issue #612

### CODE REVIEW

**Comment by amogh-jrules** [comment]
@atherdon @vadim9999 can you review this pr?

**Comment by amogh-jrules** [comment]
The travis test is failing on running npm run generateFiles, I tried it locally also, I get the same error. What is the issue here?

**Comment by atherdon** [comment]
reviewing it right now

**Comment by atherdon** [comment]
what is issue number for this pr?

**Comment by amogh-jrules** [comment]
@atherdon I think the npm run generateFiles command is causing an issue

**Comment by amogh-jrules** [comment]
> what is issue number for this pr?

Issue #612

**Comment by atherdon** [comment]
no, it's a number of this PR. i think you mistakenly copying it :)

**Comment by atherdon** [comment]
yeah, i think you solve partially an issue with updating travis.yml file - nice catch btw!

**Comment by amogh-jrules** [comment]
> no, it's a number of this PR. i think you mistakenly copying it :)

Yes my bad, its #531

**Comment by atherdon** [comment]
no problem

**Comment by amogh-jrules** [comment]
> yeah, i think you solve partially an issue with updating travis.yml file - nice catch btw!

No even after updating its causing some error, so I reverted back to the old version

**Comment by atherdon** [comment]
ok, please create a new PR and update it to the new script as you did before :)

**Comment by atherdon** [comment]
and then please jump at this task: https://github.com/GroceriStar/food-static-files-generator/issues/89

**Comment by amogh-jrules** [comment]
> ok, please create a new PR and update it to the new script as you did before :)

Ok on it

**Pull request merged**
