### PR TITLE
Exporting more JSONs

### PR DESCRIPTION
**Pull request by wahaj-47**

### CODE REVIEW

**Comment by atherdon** [comment]
I cannot publish our sd-wrapper - because we don't have `data/Grocery/example/gs-loopback-samp
le.json`

**Comment by atherdon** [comment]
i.e. build generates an error

**Comment by atherdon** [comment]
you can see it by yourself - run `yarn build`

**Comment by wahaj-47** [comment]
We 

> I cannot publish our sd-wrapper - because we don't have `data/Grocery/example/gs-loopback-samp le.json`

But we were using that JSON before.

**Comment by atherdon** [comment]
maybe you right, i don't remember the time when it went missing... what we need to do?

**Comment by wahaj-47** [comment]
Maybe it was renamed ?

**Comment by atherdon** [comment]
as you know - i commit a lot - so a lot of time we cannot trust my memory.
1. we can roll some previous version of both plugins. for example - `sd` right now have version 2. so maybe if we go before 1st major release - you'll be able to find it. or not. for some reason, I think it was done on purpose. Because I was responsible for creating sd-wrapper and I usually have a low level of mistakes like that(but sure it can be my fault or mis-delete). This is why we actually have tests
2. we can roll down our fetch plugin. and I think this is a better idea. because before - fetch contain all json files. I don't have a proper version in mind. I think you should try `1.2` but it's actually the time when I split module in two pieces. and `1.1`  will be your next target. or you can apply advanced search to closed issues in fetch - maybe we just delete it, and import was uncommented by accident

previous versions, for both of plugins you can find at "releases" tab at GitHub.

**Comment by atherdon** [comment]
i decide to check myself. at https://github.com/GroceriStar/groceristar-fetch/releases/tag/v1.2.0
I see a `data` folder(similar to `sd-wrapper`) and we don't have that file

**Comment by atherdon** [comment]
and this is what i see at `/projects/loopback`

```
const ultimateGroceryList =
  require('../../data/Grocery/example/ultimate-gl-from-loopback-server-example.json');
// const ingredients3     = require('@groceristar/sd-wrapper/lib/data/Ingredients/ingredients3.json');

const groceryListWithUserRelations =
  require('../../data/Grocery/example/grocery-with-user-relations.json')
// const ingredients3     = require('@groceristar/sd-wrapper/lib/data/Ingredients/ingredients3.json');

const dbIngredients =
  require('../../data/Ingredients/example/gs-loopback-sample.json');
// const ingredients3     = require('@groceristar/sd-wrapper/lib/data/Ingredients/ingredients3.json');

```
So I assume it answer to our problem

**Pull request merged**
