### PR TITLE
Update groceristar.teszt.js

### PR DESCRIPTION
**Pull request by Edebo**
copying the test file from groceristar-fetch to groceristar in generator folder.issue#243

## Proposed changes

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request.
If it fixes a bug or resolves a feature request, be sure to link to that issue.

## Types of changes

What types of changes does your code introduce to static food data?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] refactor
- [ ] documentation
- [ ] other

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

Are tests included?
- [ ] yes (*bugfixes and features will not be merged without tests*)
- [ ] no

Breaking Changes?
- [ ] yes (*breaking changes will not be merged unless absolutely necessary*)
- [ ] no

List any relevant issue numbers:

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by atherdon** [comment]
our next thing is to complete this PR and merge it

**Comment by atherdon** [comment]
/home/travis/build/GroceriStar/sd/generator/projects/GroceriStar/test/groceristar.teszt.js:129:1: Parsing error: Unexpected token }

**Comment by atherdon** [comment]
/home/travis/build/GroceriStar/sd/generator/projects/GroceriStar/test/groceristar.teszt.js:125:5: Parsing error: Unexpected token )

**Comment by atherdon** [comment]
```
 /home/travis/build/GroceriStar/sd/generator/projects/GroceriStar/test/groceristar.teszt.js:118:1: 'describe' is not defined.
  /home/travis/build/GroceriStar/sd/generator/projects/GroceriStar/test/groceristar.teszt.js:120:5: 'it' is not defined.
  /home/travis/build/GroceriStar/sd/generator/projects/GroceriStar/test/groceristar.teszt.js:122:7: 'expect' is not defined.
```
i think it's a last part

**Comment by Edebo** [comment]
i am so sorry for all these errors.i dont know why it is saying describe,it and expect not defined

**Comment by atherdon** [comment]
dont worry - it's actually great that we setup our test environment with help of @hirdbluebird and we can to catch this errors in seconds.
it's a similar issue to https://github.com/GroceriStar/sd/pull/374#pullrequestreview-241985154

**Comment by Edebo** [comment]
still giving the same error

**Comment by atherdon** [comment]
we just have it commented two times :) looks like it may work right now

**Comment by atherdon** [comment]
party time! ok merging it. what will be our next step?

**Comment by Edebo** [comment]
test passed.yippy.now i know why it wasnt passing from the changes you made

**Comment by atherdon** [comment]
yeah, sometimes ESLint have very strict rules, but it's actually a good thing. I mean - robots saving us tons to hours and reducing tech debt

**Pull request merged**
