### PR TITLE
upgrading exampleFiles.test.js

### PR DESCRIPTION
**Pull request by amogh-jrules**
#524

### CODE REVIEW

**Comment by amogh-jrules** [comment]
travis ci tests are failing repeatedly...

**Comment by atherdon** [comment]
then it should be fixed. what errors it's generating?

**Comment by amogh-jrules** [comment]
I'll check it out, but can you check the method I have created?

**Comment by atherdon** [comment]
i can, but want to see how you'll deal with this build error

>

**Comment by atherdon** [comment]
so log is :
```
 /home/travis/build/GroceriStar/sd/tests/testFilesCheck/exampleFiles.test.js:1:21: 'it' is defined but never used.
  /home/travis/build/GroceriStar/sd/tests/testFilesCheck/exampleFiles.test.js:7:9: 'doesFileExist' is assigned a value but never used.
  /home/travis/build/GroceriStar/sd/tests/testFilesCheck/exampleFiles.test.js:8:5: 'test' is not defined.
error Command failed with exit code 1.
```

what is not clear for you

**Comment by amogh-jrules** [comment]
> so log is :
> 
> ```
>  /home/travis/build/GroceriStar/sd/tests/testFilesCheck/exampleFiles.test.js:1:21: 'it' is defined but never used.
>   /home/travis/build/GroceriStar/sd/tests/testFilesCheck/exampleFiles.test.js:7:9: 'doesFileExist' is assigned a value but never used.
>   /home/travis/build/GroceriStar/sd/tests/testFilesCheck/exampleFiles.test.js:8:5: 'test' is not defined.
> error Command failed with exit code 1.
> ```
> 
> what is not clear for you

test is just an alias for it as per jest documentation,
doesFileExist method is called with a parameter type which is validated by the expect method call within it.

**Comment by amogh-jrules** [comment]
> Ok, tests passing and you made it similar to the code example that i shared with you. But the previous version of tests cover all cases for all files from examples folder. Is your version doing the same? I'm not sure

The travis log shows the following tests passing, i think it covers all of them
```

 PASS  tests/projects/GroceriStar/groceristar.test.js
  Groceristar method should return data
    ✓ Groceristar getKeyArrayDepAndIng return non empty string (26ms)
    ✓ Groceristar ultimateGroceryList return non empty string (53ms)
    ✓ Groceristar getDepartmentIngredients return non empty string (1ms)
    ✓ Groceristar getGroceryDepartmentsWithIngredients return non empty string (1ms)
 PASS  tests/measurementSystems.test.js
  users data files returns array
    ✓ these tests prevent any issues and problems, also to break the structure of measurementSystems (1ms)
    ✓ these tests prevent any issues and problems, also to break the structure of generatedMeasurementSystem (1ms)
  MeasurementSystem json schema testing
    ✓ validates MeasurementSystem json schema (42ms)
  generatedMeasurementSystem json schema testing
    ✓ validates generatedMeasurementSystem json schema (10ms)
 PASS  tests/measurementUnits.test.js
  users data files returns array
    ✓ these tests prevent any issues and problems, also to break the structure of measurementUnits (1ms)
    ✓ these tests prevent any issues and problems, also to break the structure of measurementUnits
   MeasurementUnits schema testing
    ✓ validates  MeasurementUnits json schema (20ms)
   generatedMeasurementUnits schema testing
    ✓ validates  generatedMeasurementUnits json schema (8ms)
 PASS  tests/nutrition.test.js
  nutritions data files returns array
    ✓ these tests prevent any issues and problems, also to break the structure of nutritions (1ms)
  nutritions2 data files returns array
    ✓ these tests prevent any issues and problems, also to break the structure of nutritions2
  test nutrition1 json-schema
    ✓ validates nutrition1 json-schema (20ms)
  nutritions2 json schema testing
    ✓ validates nutritions2 json schema (7ms)
 PASS  tests/nutritionalAttributes.test.js
  nutritionalAttributes data files returns array
    ✓ these tests prevent any issues and problems, also to break the structure of nutritionalAttributes (11ms)
  testng for nutritionalAttribute json data schema
    ✓ validates nutritionalAttribute json schema (9ms)
 PASS  tests/userGrocery.test.js
  userGrocery data files returns array
    ✓ these tests prevent any issues and problems, also to break the structure of userGrocery (1ms)
  testing userGrocery schema and also requiring it
    ✓ validates UserGrocery json schema (21ms)
 PASS  tests/dash.test.js
  this test prevents to any issues and problems, also to break the structure of dash data
    ✓ dash data files returns object (1ms)
  test dash test json schema
    ✓ validates my json (9ms)
 PASS  tests/firstVeganGLMC.test.js
  firstVeganGLMC data files returns array
    ✓ these tests prevent any issues and problems, also to break the structure of firstVeganGLMC (1ms)
  test firstVeganGLMC json
    ✓ validates my json (9ms)
 PASS  tests/measurement.test.js
  measurements data files returns array
    ✓ these tests prevent any issues and problems, also to break the structure of measurement (1ms)
  tests measurement json schema
    ✓ validates my json (9ms)
 PASS  tests/halfCup.test.js
  this test prevents to any issues and problems, also to break the structure of cup1_2 data
    ✓ cup1_2 data files returns object (1ms)
  tests halfCup json schema
    ✓ validates my json (20ms)
 PASS  tests/mealCalendar.test.js
  mealcalendar data files returns array
    ✓ these tests prevent any issues and problems, also to break the structure of mealcalendar (1ms)
  test mealcalender json
    ✓ validates my json (9ms)
 PASS  tests/departments.test.js
  departments data files returns array
    ✓ these tests prevent any issues and problems, also to break the structure of departments (1ms)
  test department  json schema
    ✓ validates my json (9ms)
 PASS  tests/ingredients.test.js
  ingredients data files returns array
    ✓ these tests prevent any issues and problems, also to break the structure of ingredients (1ms)
  test ingerdients json
    ✓ validates my json (10ms)
 PASS  tests/cuisine.test.js
  this test prevents to any issues and problems, also to break the structure of cuisines data files
    ✓ cuisines data files returns array (1ms)
  tests for cuisine schema
    ✓ validates cuisine json (9ms)
 PASS  src/index.test.js
  testing if allergies file are exists
    ✓ xxx (1ms)
 PASS  tests/favorites.test.js
  favorites data files returns array
    ✓ these tests prevent any issues and problems, also to break the structure of favorites (1ms)
  tests favorites json schema
    ✓ validates my json (10ms)
 PASS  tests/tablespoon.test.js
  this test prevents to any issues and problems, also to break the structure of tablespoon_1 data
    ✓ tablespoon_1 data files returns object (1ms)
  test for tablespoon json schema
    ✓ validates tablespoon json schema (20ms)
 PASS  tests/recipe4.test.js
  recipe data files returns array
    ✓ these tests prevent any issues and problems, also to break the structure of recipe (1ms)
  test recipe json-schema
    ✓ validates recipe json-schema (10ms)
 PASS  tests/course.test.js
  courses data files returns array
    ✓ this test prevents to any issues and problems, also to break the structure of courses (1ms)
  tests for course schema
    ✓ validates course json (9ms)
 PASS  tests/grocery.test.js
  grocery data files returns array
    ✓ these tests prevent any issues and problems, also to break the structure of grocery (1ms)
  tests grocery json schema
    ✓ validates my json (10ms)
 PASS  tests/cookingTimes.test.js
  this test prevents to any issues and problems, also to break the structure of cookingTimes data
    ✓ cookingTimes data files returns object (1ms)
  test cookingTimes json schema
    ✓ validates cookingTimes json (10ms)
 PASS  tests/teaspoon.test.js
  this test prevents to any issues and problems, also to break the structure of teaspoon_1 data
    ✓ teaspoon_1 data files returns object (1ms)
  testng for teaspoon json data schema
    ✓ validates my json (10ms)
 PASS  tests/users.test.js
  users data files returns array
    ✓ these tests prevent any issues and problems, also to break the structure of users (1ms)
  testing for user json schema
    ✓ validates users json (24ms)
 PASS  tests/pinch.test.js
  this test prevents to any issues and problems, also to break the structure of pinch data
    ✓ pinch data files returns object (1ms)
  testng for pinch json data schema
    ✓ validates pinch json file schema (9ms)
 PASS  tests/menu.test.js
  menu data files returns array
    ✓ these tests prevent any issues and problems, also to break the structure of menu (1ms)
  types json schema testing
    ✓ validates type json schema (10ms)
 PASS  tests/quarterCup.test.js
  this test prevents to any issues and problems, also to break the structure of quaterCup data
    ✓ quaterCup data files returns object (1ms)
  test quarter cup json schema
    ✓ validates my json (9ms)
 PASS  tests/types.test.js
  types data files returns array
    ✓ these tests prevent any issues and problems, also to break the structure of types (1ms)
  types json schema testing
    ✓ validates type json schema (9ms)
 PASS  tests/quart.test.js
  this test prevents to any issues and problems, also to break the structure of quart data
    ✓ quart data files returns object (1ms)
  testng for quart json data schema
    ✓ validates quart json-schema (10ms)
 PASS  tests/items.test.js
  items data files returns array
    ✓ these tests prevent any issues and problems, also to break the structure of items (1ms)
  test my items json
    ✓ validates my json (20ms)
 PASS  tests/attribute.test.js
  attributes data files returns array
    ✓ these tests prevent any issues and problems, also to break the structure of attributes (1ms)
  tests for attribute schema
    ✓ validates allergy json (9ms)
 PASS  tests/pint.test.js
  this test prevents to any issues and problems, also to break the structure of pint data
    ✓ pint data files returns object (1ms)
  test pint json schema
    ✓ validates pint json schema (9ms)
 PASS  tests/gallon.test.js
  this test prevents to any issues and problems, also to break the structure of gallon data
    ✓ gallon data files returns object (1ms)
  test gallon json schema
    ✓ validates my json (9ms)
 PASS  tests/allergy.test.js
  tests for allergy
    ✓ allergies data files returns array (1ms)
  tests for allergy schema
    ✓ validates allergy json (8ms)
 PASS  tests/cup1_8.test.js
  this test prevents to any issues and problems, also to break the structure of cup1_8 data
    ✓ cup1_8 data files returns object (1ms)
  test cup1_8 json schema
    ✓ validates my json (22ms)
 PASS  tests/cup3_4.test.js
  this test prevents to any issues and problems, also to break the structure of cup3_4 data
    ✓ cup3_4 data files returns object (1ms)
  test cup3_4 json schema
    ✓ validates my json (9ms)
 PASS  tests/holiday.test.js
  holidays data files returns array
    ✓ these tests prevent any issues and problems, also to break the structure of holiday (1ms)
  tests holiday json schema
    ✓ validates my json (8ms)
 PASS  tests/cup1.test.js
  this test prevents to any issues and problems, also to break the structure of cup1 data
    ✓ cup1 data files returns object (1ms)
  test cup1 json schema
    ✓ validates my jason (9ms)
 PASS  tests/diet.test.js
  diets data files returns array
    ✓ test for Diet (1ms)
  tests diet json schema
    ✓ validates my json (20ms)
 PASS  tests/groceryListWithUserRelations.test.js
  groceryListWithUserRelations data files returns array
    ✓ these tests prevent any issues and problems, also to break the structure of groceryListWithUserRelations (1ms)
 PASS  tests/testFilesCheck/exampleFiles.test.js
  tests for example file existance
    ✓ validates that allergy example file exists (1ms)
 PASS  tests/ultimateGroceryList.test.js
  ultimateGroceryList data files returns array
    ✓ these tests prevent any issues and problems, also to break the structure of ultimateGroceryList (1ms)
 PASS  tests/dbIngredients.test.js
  dbIngredients data files returns array
    ✓ these tests prevent any issues and problems, also to break the structure of dbIngredients (1ms)
 PASS  tests/recipe.ck.test.js
  recipeCk data files returns array
    ✓ these tests prevent any issues and problems, also to break the structure of recipeCk (1ms)
Test Suites: 43 passed, 43 total
Tests:       88 passed, 88 total
```

**Comment by atherdon** [comment]
travis ci shows only tests that isset. it cannot catch tests that doesn't
called
if you run tests at master branch from repository - you'll see more of them.
ask me question if it's not clear what i mean. because looks like we arguing

>

**Comment by amogh-jrules** [comment]
> travis ci shows only tests that isset. it cannot catch tests that doesn't called if you run tests at master branch from repository - you'll see more of them. ask me question if it's not clear what i mean. because looks like we arguing
> […](#)

no no of course not, can you tell me how to run tests on my local machine? Im not so sure...
Also I dont understand what you mean by isset

**Comment by atherdon** [comment]
i mean that before your changes we have this number of tests
image


This is why when i'm coding something - i didn't delete previous versions totally. because i'm always not sure about my code. and it gives me an ability to compare things

compare your file with this version: https://github.com/GroceriStar/sd/blob/master/tests/testFilesCheck/exampleFiles.test.js

take some time and if you'll not be able to do it yourself - buzz me - but before spend some time

**Comment by atherdon** [comment]
ohh, we also have some changes at exampleFiles - this conflict should be resolved as well. Please tell me if all of this info is hard to digest from the begining and i'll help you a bit

**Comment by amogh-jrules** [comment]
Ok, I'll figure it out

**Comment by amogh-jrules** [comment]
Hey, I looked into the conflict, but it looks like its just an addition of the old code on the new one...
I'm looking into the Travis CI test which are missing in my commit

**Comment by amogh-jrules** [comment]
I have included all the tests now 😅
image

**Comment by atherdon** [comment]
@vadim9999 please take a look

@amogh-jrules we still have conflicts at `exampleFiles.test.js`

**Comment by amogh-jrules** [comment]
> @vadim9999 please take a look
> 
> @amogh-jrules we still have conflicts at `exampleFiles.test.js`

Oh it's just the ordering and I have made it correct in my version, in the conflicting version, the function is called before the declaration

**Comment by atherdon** [comment]
@vadim9999 what do you think we should do here? we can wait or maybe you can checkout this PR and fix merge conflict so all of us can move forward?

**Comment by vadim9999** [comment]
Ok I will find out what is the problem

**Comment by vadim9999** [comment]
@amogh-jrules I think the problem is with a comma that you have added after each function call. Please delete it

**Comment by amogh-jrules** [comment]
> @amogh-jrules I think the problem is with a comma that you have added after each function call. Please delete it

Oh sorry, my bad, will add another commit right away

**Comment by amogh-jrules** [comment]
I have resolved the conflicts and the commit passes the tests. Sorry for the trouble folks, will try to improve on future commits
Thanks!

**Comment by vadim9999** [comment]
No problem

**Pull request merged**
