### PR TITLE
issues number #268 #263 #274 #275

### PR DESCRIPTION
**Pull request by EbrahimKreem**

### CODE REVIEW

**Comment by atherdon** [comment]
#268 Did you test how this module work?
And if you can - please add an explanation at Readme as well about this module, so everyone will be ready to this change

**Comment by EbrahimKreem** [comment]
s

**Comment by atherdon** [comment]
if you have time @EbrahimKreem you can also attach a PR, where you run a `code-fix` script. So our code will be ESLinted. and Vadim will approve your PR when he'll have time

**Comment by EbrahimKreem** [comment]
ok

**Comment by vadim9999** [comment]
@EbrahimKreem I haven't assign this task to you. Also I haven't describe it. Let's replace task for this https://github.com/GroceriStar/sd/issues/278. Please change to es5

**Comment by atherdon** [comment]
as we have a conflict at jsonlint - i think this branch should be rebased

**Comment by vadim9999** [comment]
https://github.com/GroceriStar/sd/issues/275

**Comment by vadim9999** [comment]
It's hard to check many task in one PR. In result we have:

---
Issue https://github.com/GroceriStar/sd/issues/268
1. Installed rollup in commit https://github.com/GroceriStar/sd/pull/269/commits/4fcae816974fbd5a6ff433534d1dcad94b398efb 
2. Added into Readme explanation about rollup notifier in commit https://github.com/GroceriStar/sd/pull/269/commits/2f09ea80701e5915146a3c446b87a1c2176e4a88
**Note** add explanation into Readme how to run rollup 
---

In issue https://github.com/GroceriStar/sd/issues/263 and https://github.com/GroceriStar/sd/issues/278 (the same)
1. tests working on es5

---

In issue https://github.com/GroceriStar/sd/issues/274 
1. Moved into src and changed filepaths to utils in some files that was used it https://github.com/GroceriStar/sd/pull/269/commits/053cc5129c2ead72cbc2642420e029d43bcac2bd

---

In issue https://github.com/GroceriStar/sd/issues/275
1. moved jsonnlint into src/data in https://github.com/GroceriStar/sd/pull/269/commits/3af104e42d51abd8bea7ed0bba559ad609bb7a82

---
Additional:
1. I suppose was executed command  `code-fix` in  https://github.com/GroceriStar/sd/pull/269/commits/a0cbf2cf90b8d9d74e2a80a916a2168550fb5ee4

@atherdon what do you think can we merge after adding changes to Reame about how to run eollup and fix conflict?

**Comment by atherdon** [comment]
when conflicts will be resolved - i think we can merge it.
And if something will be broken - we'll need just quickly react and fix it.
@vadim9999 do you want me to run this PR at separated machine and check if everything is ok?

**Comment by vadim9999** [comment]
@atherdon No

**Comment by atherdon** [comment]
btw, if you want to run some PRs of our interns - without long processing, you can use https://gitpod.io - very cool thing for code reviewing process

**Comment by vadim9999** [comment]
@atherdon thanks I will try

**Comment by atherdon** [comment]
Vadim, sidenote - can you please close tasks, when we'll merge this PR - because right now it's hard for me to navigate at Issues tab

**Comment by vadim9999** [comment]
ok

**Comment by atherdon** [comment]
I think we're waiting for @EbrahimKreem rebase and it can be merged, right? just trying to follow whole progress here...

**Comment by vadim9999** [comment]
yes all right

**Comment by vadim9999** [comment]
merge

**Pull request merged**
