### PR TITLE
Variables imported from files.js

### PR DESCRIPTION
**Pull request by wahaj-47**

### CODE REVIEW

**Comment by vadim9999** [comment]
@wahaj-47 please change import path on files.js that is located in root of project. we have two files.js in root of project and in folder src

**Comment by wahaj-47** [comment]
You want me to import variables from file.js in src folder into files.js in the root ?

**Comment by vadim9999** [comment]
@wahaj-47 No, I want that you use importing variables from files.js that is located in root directory(sd/files.js).  Because files.js using path.resolver

**Comment by wahaj-47** [comment]
What about the files not being exported by files.js ? 
The one in the root directory.

**Comment by vadim9999** [comment]
thne import and export object that you will need to use in tests in files.js

**Comment by vadim9999** [comment]
@wahaj-47 you can leave file tests that elnur have added

**Pull request merged**
