### PR TITLE
update readme.md

### PR DESCRIPTION
**Pull request by uniyalprashant9**

### CODE REVIEW

**Comment by uniyalprashant9** [comment]
Sure, I will upgrade the splitObject() so that it can split any json file to its respective directory given the path of the file as a parameter.

I will add tests later on after upgrading splitObject() and will put it in seperate file to avoid conflicts with other modules in writeFile.js.

**Comment by atherdon** [comment]
can you please create 2 tasks here and assign them to yourself - so we wouldn't forget this conversation?

**Comment by uniyalprashant9** [comment]
### New Tasks to be done.

- [ ] Upgrade splitObject()
- [ ] Add tests for splitObject()
- [ ] Add tests for getList(), getListContent()

**Comment by atherdon** [comment]
Ok, but use https://github.com/GroceriStar/sd/issues

**Comment by uniyalprashant9** [comment]
Ok , I have moved this to issues 😃.

**Comment by atherdon** [comment]
perfect!

**Pull request merged**
