### PR TITLE
upd

### PR DESCRIPTION
**Pull request by elnur004**
## Proposed changes

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request.
If it fixes a bug or resolves a feature request, be sure to link to that issue.

## Types of changes

What types of changes does your code introduce to static food data?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] refactor
- [ ] documentation
- [ ] other

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

Are tests included?
- [ ] yes (*bugfixes and features will not be merged without tests*)
- [ ] no

Breaking Changes?
- [ ] yes (*breaking changes will not be merged unless absolutely necessary*)
- [ ] no

List any relevant issue numbers:

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by vadim9999** [comment]
@elnur004 Which task is related to this PR?

**Comment by elnur004** [comment]
> @elnur004 Which task is related to this PR?

@vadim9999 #236 
is there necessary to create a function that will display all objects?

**Comment by vadim9999** [comment]
@elnur004 yeah

**Comment by elnur004** [comment]
@vadim9999 and is that function which i've pulled request a correct way?

**Comment by vadim9999** [comment]
@elnur004 I have run you play.js and it`s not working. The problem is in importing filesObjects

**Comment by elnur004** [comment]
@vadim9999 but what is a problem?
i have run play.js with terminal, it worked correctly

**Comment by elnur004** [comment]
@vadim9999 if there problem with importing, why everything works with the terminal absolutely?

**Comment by vadim9999** [comment]
Here is my console log after running this command
```
node ./generator/play/play.js
```

```
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '../../filesObjects'
```

**Comment by vadim9999** [comment]
Ok good

**Comment by vadim9999** [comment]
It's working. Then create a function that will display all objects.

**Comment by vadim9999** [comment]
Oh Sorry I see you have done it

**Pull request merged**
