### PR TITLE
fix code automatically before a commit

### PR DESCRIPTION
**Pull request by EbrahimKreem**
fix code automatically before a commit using lint-staged and husky

### CODE REVIEW

**Comment by atherdon** [comment]
hmm, you added an interesting tool here. Ok, not sure if we talk about husky setup, but ok - I wanted to use it.
Question: can you also add a configuration to Travis CI, so it will run there as well?

**Comment by EbrahimKreem** [comment]
ok

**Comment by EbrahimKreem** [comment]
I think it's useful for fixing the code before a commit so no need for other devs to run` npm run code-fix`

**Comment by atherdon** [comment]
I can merge this PR but will put details here after that. so we'll have in one place.

**Comment by EbrahimKreem** [comment]
> Question: can you also add a configuration to Travis CI, so it will run there as well?
I think there is no need to put any configuration there because the code will be fixed before any commit

**Comment by atherdon** [comment]
1) can you add the same changes at https://github.com/GroceriStar/groceristar-fetch as well?

**Comment by EbrahimKreem** [comment]
ok

**Comment by atherdon** [comment]
> I think there is no need to put any configuration there because the code will be fixed before any commit

Not correct. Travis CI will work on builds at PRs, so it's an important thing

**Comment by EbrahimKreem** [comment]
what about travis ci should I add it there

**Comment by atherdon** [comment]
you should configure our https://github.com/GroceriStar/sd/blob/master/.travis.yml
and similar to how we run it right now - we'll run the same script on CI build. google it i think there plenty tutorials related to this part of config

**Comment by atherdon** [comment]
2) did we actually finish our work on #387?

**Comment by atherdon** [comment]
3) I want to add coveralls
https://github.com/GroceriStar/sd/blob/master/docs/Readme.md#add-coveralls

4) we need to add more cool looking stages to our travis config(it's not important for now maybe, but will be important later)

**Comment by EbrahimKreem** [comment]
> you should configure our https://github.com/GroceriStar/sd/blob/master/.travis.yml
and similar to how we run it right now - we'll run the same script on CI build. google it i think there plenty tutorials related to this part of config

ok

**Comment by atherdon** [comment]
travis is pretty useful tool - you'll like it

**Comment by EbrahimKreem** [comment]
ok so now I should run the `npm run code-fix` before the build like this
`script:
 - npm run code-fix
  - npm test
  - npm run jsonlint
  - npm run build`

**Comment by EbrahimKreem** [comment]
and then add the `npm run test:cover` in the same script

`script:
npm run code-fix
npm test
npm run jsonlint
npm run build
npm run test:cover``

**Comment by atherdon** [comment]
what test:cover doing?

not sure about your order, but husky should run before build - it's 100%

**Comment by atherdon** [comment]
maybe this information will help with point 4: https://github.com/GroceriStar/sd/blob/master/docs/Readme.md#travis-ci

**Comment by EbrahimKreem** [comment]
> what test:cover doing?

do you want to add test coveralls to stages or no?

**Comment by atherdon** [comment]
yes, i want - because it'll show coverage at PR and it will help me and Vadim when he'll be back with code review

**Comment by atherdon** [comment]
> 1. did we actually finish our work on #387?

this question is still pending for me

**Comment by EbrahimKreem** [comment]
> did we actually finish our work on #387?

I didn't check this issue lastly but when I complete this tool I will check it

**Comment by atherdon** [comment]
thank you! because husky is more like an improvement, but that part is actually important not only for our company. i'm in contact with few food tech startups and they interested to see what we did

**Comment by atherdon** [comment]
5. as we going all in - I want it! https://github.com/conventional-changelog/commitlint
6. - **[How to write a Javascript library automating releases with semantic release]**(https://egghead.io/lessons/javascript-how-to-write-a-javascript-library-automating-releases-with-semantic-release)
- **[Semantic release]**(https://github.com/semantic-release/semantic-release)

**Comment by atherdon** [comment]
xxx

**Pull request merged**
