### PR TITLE
moved files.js and filesObjects.js in to src

### PR DESCRIPTION
**Pull request by Beni03**
## Proposed changes

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request.
If it fixes a bug or resolves a feature request, be sure to link to that issue.

## Types of changes

What types of changes does your code introduce to static food data?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] refactor
- [ ] documentation
- [ ] other

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

Are tests included?
- [ ] yes (*bugfixes and features will not be merged without tests*)
- [ ] no

Breaking Changes?
- [ ] yes (*breaking changes will not be merged unless absolutely necessary*)
- [ ] no

List any relevant issue numbers:

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by atherdon** [comment]
we have conflics here - can you solve it?

**Comment by atherdon** [comment]
but your code changes is good = i just cannot merge them because of this branch confict

**Comment by Beni03** [comment]
Yes, I can solve it

**Comment by atherdon** [comment]
ok, but check why filesObjects.js has conflicts

**Comment by Beni03** [comment]
Ok.
quick question : can you see my code update (added "/")

**Comment by atherdon** [comment]
yes - just reviewed that change in path

**Comment by Beni03** [comment]
Ok

**Comment by atherdon** [comment]
tell me if there any problem
maybe you didn't sync your fork with our master and don't see merge conflicts?

**Comment by Beni03** [comment]
I think filesObjects.js has conflicts because of the conflicts in files.js.
So I think first that conflict has to get resolved.
Am I right?

**Comment by atherdon** [comment]
```
node ./generator/generateFiles.js
internal/modules/cjs/loader.js:626
    throw err;
    ^
Error: Cannot find module '../files'
    at Object.<anonymous> (/home/travis/build/GroceriStar/sd/generator/generateArray.js:10:5)

```

**Comment by Beni03** [comment]
Oh ok. Got it. I Just updated my fork but still could not see this
conflict. will look in to it

**Comment by Beni03** [comment]
Sorry for taking long time on this simple task. Will start to work on Travis for testing the code before sending pull requests.

**Comment by atherdon** [comment]
you should update this line
https://github.com/GroceriStar/sd/blob/master/generator/generateArray.js#L10

**Comment by Beni03** [comment]
Yes, I updated but still I am getting some conflict I think

**Comment by atherdon** [comment]
did you push your changes to this PR?

**Comment by atherdon** [comment]
because i don't see that changes

**Comment by atherdon** [comment]
haha - I think we catch a big fish here :) 
do you have other tasks to work on? i'll ship some small improvement in 20 minutes - because we cannot solve it in a straight way - we should go smart

**Comment by Beni03** [comment]
Oh ok.
I think I have task #399 to work on

**Comment by atherdon** [comment]
#399 is a pull request. or it's from groceristar-fetch repository?

**Comment by atherdon** [comment]
at this branch i'll continue work on this task. just to let you know: https://github.com/GroceriStar/sd/tree/aliases-for-files-utils

I got it - you mean this task: https://github.com/GroceriStar/groceristar-fetch/issues/399

**Comment by Beni03** [comment]
Ok

**Comment by atherdon** [comment]
@Beni03 can you sync your fork with master? I finish my changes, so we'll be able to solve this task today

**Comment by atherdon** [comment]
thanks!

**Comment by atherdon** [comment]
can you rebase your PR not with master but with this branch `pr/489` please. so my new changes will be added to your PR
whole path to check at github: https://github.com/GroceriStar/sd/tree/pr/489

**Comment by atherdon** [comment]
nope, you actually rebase it with master branch. at your cli replace `master` with `pr/489`

I think we have really good practice with git here :)

**Comment by atherdon** [comment]
Ok - we did it!
xxx

**Comment by Beni03** [comment]
Yay!!! 
Thanks for helping me!

**Pull request merged**
