### PR TITLE
addons done

### PR DESCRIPTION
**Pull request by siddharthp538**
## Proposed changes

  This PR deals with the addon changes on the dash.test.js file.

## Types of changes

What types of changes does your code introduce to static food data?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] refactor
- [ ] documentation
- [x] other

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

Are tests included?
- [x] yes (*bugfixes and features will not be merged without tests*)
- [ ] no

Breaking Changes?
- [ ] yes (*breaking changes will not be merged unless absolutely necessary*)
- [x] no

List any relevant issue numbers:

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by atherdon** [comment]
please rebase your fork - right now we have conflicts

**Comment by siddharthp538** [comment]
call u tell me the command? sorry never did rebase before.

**Comment by atherdon** [comment]
not a problem. it's actually cool - because i'll also teach you how to use git.
read it here: https://blog.algolia.com/master-git-rebase/
https://github.com/ChickenKyiv/awesome-git-article#forking-pull-requests
https://gist.github.com/CristinaSolana/1885435

**Comment by siddharthp538** [comment]
@atherdon i did the rebase.

**Comment by atherdon** [comment]
#423

**Comment by siddharthp538** [comment]
> #423

**Comment by atherdon** [comment]
emm. you want to close pull request?

**Comment by siddharthp538** [comment]
> emm. you want to close pull request?

no. by mistake. sorry. how do i undo it?

**Comment by atherdon** [comment]
don't worry about it. just be careful later. go to the next file, please

>

**Comment by siddharthp538** [comment]
> don't worry about it. just be careful later. go to the next file, please
> […](#)

I think we are not done with #423 yet.

**Comment by atherdon** [comment]
yes you right. you made changes for only one file. and you need to apply
option 1 changes to other test files as well

**Comment by siddharthp538** [comment]
> yes you right. you made changes for only one file. and you need to apply option 1 changes to other test files as well

sure, on it.

**Pull request closed without merging**
