### PR TITLE
upd

### PR DESCRIPTION
**Pull request by elnur004**
## Proposed changes

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request.
If it fixes a bug or resolves a feature request, be sure to link to that issue.

## Types of changes

What types of changes does your code introduce to static food data?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] refactor
- [ ] documentation
- [ ] other

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

Are tests included?
- [ ] yes (*bugfixes and features will not be merged without tests*)
- [ ] no

Breaking Changes?
- [ ] yes (*breaking changes will not be merged unless absolutely necessary*)
- [ ] no

List any relevant issue numbers:

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by atherdon** [comment]
https://travis-ci.org/GroceriStar/sd/jobs/535964629

**Comment by elnur004** [comment]
@atherdon i guess maybe need to change `export default` to `export` in files.js file?
cause i don't determine exactly where is a problem arises.

**Comment by atherdon** [comment]
emm, this solution is not correct. 
main work of index.js is to collect all files and export them to the next - Parent level. 

with your changes at index.js
```
import {
    cookingTimes, 
    cup1
} from './files.js'
```

< - you just disabled 80% of our functionality :) But we need it. try to console.log() `files` object and you will understand how to grab that 2 variables. 
Not a problem at all - but we need to change that

**Comment by atherdon** [comment]
`export default` to `export { something }` is just different cases.

when you have a good code(as we have) - you have one export per file. and in order to make it short- it named export default.

if you in hurry - and coding not perfect code -you can have a few "something" at your file. and you need another version of exporting. in our case `export { data }` is only for combining all files into one entity.

**Comment by elnur004** [comment]
@atherdon when i try to test file, there shows up such an error. 
may you help to solve this problem, please?

Screen Shot 2019-05-24 at 01 24 57

**Comment by atherdon** [comment]
please tell me how do you trying to run this module?
if it will be easy for you = you can install Loom chrome extension and make a video using it

**Comment by atherdon** [comment]
first thing that i see here - we don't have `index.js` in our root folder. but we have `index.js` in our `src` folder.
next thing is: `index.js` at `src` folder is not compiled version and it may not be runnable by `node src/index.js`

**Comment by vadim9999** [comment]
@elnur004 how it's going with this PR?

**Comment by elnur004** [comment]
@vadim9999 i can't test files with my editor. there shows up error message.
and i don't know how to solve it. i specified it via the image above.

**Comment by vadim9999** [comment]
@elnur004 To run all file tests that exist in this project you can run this command
```
npm run test
```
if you want to run single file test
```
npm run test index.test.js
```

**Comment by vadim9999** [comment]
@elnur004 Do you have problems with testing files?

**Pull request closed without merging**
