### PR TITLE
test for getFileInfo and path fix in writeFile.js and src/utils.js

### LINKED ISSUE #424: We need to split our big object with grocery lists into separated files, each file = one grocery list object
i keep it without good task explanation for a reason. want to provoke a discussion here.
Please ask your questions. @uniyalprashant9

### PR DESCRIPTION
**Pull request by uniyalprashant9**
Fixes #424

### CODE REVIEW

**Comment by uniyalprashant9** [comment]
Its is working in my system even in longer paths
Screenshot (5)

But path.resolves() fails in resolving paths in travis ci :|
Screenshot (6)

**Comment by atherdon** [comment]
you rework that method or i should be unhappy?

>

**Comment by uniyalprashant9** [comment]
i am working on it

**Comment by atherdon** [comment]
then i'm sad... life is not fair for me

**Comment by uniyalprashant9** [comment]
finally, after spending hours on google I made it :)

**Comment by uniyalprashant9** [comment]
@atherdon

**Comment by atherdon** [comment]
looka nixe!

**Comment by atherdon** [comment]
@vadim9999 please review it

**Comment by atherdon** [comment]
@uniyalprashant9 did you update the main method or only tests?

**Comment by uniyalprashant9** [comment]
> @uniyalprashant9 did you update the main method or only tests?

I updated only tests.
Buts yes I need to update methods also.

**Comment by atherdon** [comment]
what i can say...

xxx

**Comment by atherdon** [comment]
while Vadim reviewing your code, upgrade ```splitObject``` i think it can be improved

**Comment by atherdon** [comment]
@uniyalprashant9 let's also add a backward method, that will combine splited files into big one. But do it in more elegant way. as last attribute - we'll pass a callback, that will operate structure of `object` inside of that array.

for example. 
I want to combine all grocery lists together. but for one case i want to have
```
- grocery
  - id
  - name
  - ingredients
  - departments
  - purchased
```

for the second case

```
- grocery
  - id
  - name
  - items
    - all
    - purchased
```
and i want to do manipulations with structures at callbacks. tell me if something is not clear

Plus, in the end it should call a write file for sure...

**Comment by atherdon** [comment]
and fix these new todos that I just added

**Comment by uniyalprashant9** [comment]
> and fix these new todos that I just added

@atherdon  I some made changes please review it.

**Comment by atherdon** [comment]
waiting for Vadim approval. he is now reviewing PRs, so i can have more free time

**Comment by uniyalprashant9** [comment]
> @uniyalprashant9 let's also add a backward method, that will combine splited files into big one. But do it in more elegant way. as last attribute - we'll pass a callback, that will operate structure of `object` inside of that array.
> 
> for example.
> I want to combine all grocery lists together. but for one case i want to have
> 
> ```
> - grocery
>   - id
>   - name
>   - ingredients
>   - departments
>   - purchased
> ```
> 
> for the second case
> 
> ```
> - grocery
>   - id
>   - name
>   - items
>     - all
>     - purchased
> ```
> 
> and i want to do manipulations with structures at callbacks. tell me if something is not clear
> 
> Plus, in the end it should call a write file for sure...

shall we do this in a seperate issue?

**Comment by atherdon** [comment]
@uniyalprashant9 awesome that you suggest it. create a separated issue, copy-paste this comment there and start to work on it

**Comment by uniyalprashant9** [comment]
> @uniyalprashant9 awesome that you suggest it. create a separated issue, copy-paste this comment there and start to work on it

Sure 😄

**Comment by uniyalprashant9** [comment]
@atherdon  @vadim9999  The changes I made in writefile.js might resolve issue #559

**Pull request merged**
