### PR TITLE
create project file

### PR DESCRIPTION
**Pull request by elnur004**

### CODE REVIEW

**Comment by elnur004** [comment]
@vadim9999 hi.
what to do now?

**Comment by vadim9999** [comment]
@elnur004 in src/files.js change https://github.com/GroceriStar/sd/blob/master/src/files.js#L49 import from all of this on cooking_times because we haven't this import variables.

**Comment by elnur004** [comment]
how to do this?

**Comment by vadim9999** [comment]
@elnur004 Now we have 
```
import { 
  frenchBeans,
  sprouts,
  jacketPotato,
  sweetPotato,
  kale,
  leek,
  broccoli,
  carrots,
  mushrooms,
  onions_shallots,
  parsnips,
  peppers,
  marrow_squash,
  sweetcorn,
  courgettes 
 } from '../cooking_times'
```
delete all in curly brackets and insert there cooking_times

**Pull request merged**
