### PR TITLE
reduce duplicates for parsing csv

### PR DESCRIPTION
**Pull request by EbrahimKreem**
## Proposed changes

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request.
If it fixes a bug or resolves a feature request, be sure to link to that issue.

## Types of changes

What types of changes does your code introduce to static food data?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] refactor
- [ ] documentation
- [ ] other

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

Are tests included?
- [ ] yes (*bugfixes and features will not be merged without tests*)
- [ ] no

Breaking Changes?
- [ ] yes (*breaking changes will not be merged unless absolutely necessary*)
- [ ] no

List any relevant issue numbers:

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by atherdon** [comment]
ok, lets think how to fix some codeclimte issues

**Comment by atherdon** [comment]
#387

**Comment by atherdon** [comment]
we started to work on fixing this issue with @Edebo and partially it will be done soon.
Not sure if we need to do something about it - we can just wait.

**Comment by atherdon** [comment]
please rebase your PR

**Comment by atherdon** [comment]
when you'll do it i assume we'll have less issues - some of that notifications were fixed

**Comment by atherdon** [comment]
@wahaj-47 your changes has conflictis with this PR - can you check this code and tell me what should we do?

**Comment by atherdon** [comment]
@EbrahimKreem let's chat here and find out what we need to do

**Comment by atherdon** [comment]
can you sync your fork and create a separated pr? it will be hard to merge this PR

**Comment by EbrahimKreem** [comment]
Ok I think I will close this pr and fork it again

**Comment by atherdon** [comment]
:( I keep this PR in order to see what changes you've made and compare your
code with our actuall csv parser. but maybe closing it - is a good idea

**Pull request closed without merging**
