### PR TITLE
created test.js file

### PR DESCRIPTION
**Pull request by ronniebhatt**

### CODE REVIEW

**Comment by atherdon** [comment]
your pull have conflicts with my changes, please rebase your branch and resolve a conflict

**Comment by ronniebhatt** [comment]
i have send all the import and export to the other file which i have created , so what conflict has occurred in the index.js file or what should i put to index.js file

**Comment by atherdon** [comment]
The problem is - you cannot just remove everything from index.js - because it's the main - starting point of our module. After your changes everything will be broken

**Comment by atherdon** [comment]
Ok, conflict solved - tell me how do you think you can solve this task

**Comment by ronniebhatt** [comment]
Actually, I thought i have to remove all the content from index.js to another file, beacuse as per the index.js all import ,export are done already so that's why i moved the content to another fie

sorry for that, as i am on my early stage of career i fell little difficult on understanding question

**Comment by atherdon** [comment]
not a problem.yes, you need to move imports to another file. name that file `files.js`. and then you need to connect it at index.js and export all files from `files.js` at index.js

**Comment by ronniebhatt** [comment]
ok , i will do that .

**Comment by atherdon** [comment]
ok, import at index.js looks fine.
but please add an export too(yes, right now it will look the same as export from index.js)

**Comment by atherdon** [comment]
Ok, good - this is what i actually want to have. Merging

**Pull request merged**
