### PR TITLE
 created loops for two files

### PR DESCRIPTION
**Pull request by elnur004**
## Proposed changes

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request.
If it fixes a bug or resolves a feature request, be sure to link to that issue.

## Types of changes

What types of changes does your code introduce to static food data?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] refactor
- [ ] documentation
- [ ] other

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

Are tests included?
- [ ] yes (*bugfixes and features will not be merged without tests*)
- [ ] no

Breaking Changes?
- [ ] yes (*breaking changes will not be merged unless absolutely necessary*)
- [ ] no

List any relevant issue numbers:

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by atherdon** [comment]
our testing script show us that we have errors.
this is an error message:
```
  /home/travis/build/GroceriStar/sd/src/index.js:30:8: Identifier 'cooking_times' is not in camel case.
  /home/travis/build/GroceriStar/sd/src/index.js:30:27: '/home/travis/build/GroceriStar/sd/src/files.js' imported multiple times.
  /home/travis/build/GroceriStar/sd/src/index.js:32:18: '/home/travis/build/GroceriStar/sd/src/files.js' imported multiple times.
  /home/travis/build/GroceriStar/sd/src/index.js:46:16: 'files' is not defined.
error Command failed with exit code 1.
```
tell me if something is not clear.

**Comment by atherdon** [comment]
ok, cool. But there is still an issue with cooking times variable. and i think you just need to check this file and you'll understand how to deal with it: https://github.com/GroceriStar/sd/blob/master/src/files.js
when you'll update it and all will work - i'll be able to merge this PR

**Comment by atherdon** [comment]
we have another small issue with that variable.
this is a log:
```
[!] Error: 'cookingTimes' is not exported by src/files.js
https://rollupjs.org/guide/en#error-name-is-not-exported-by-module-
src/index.js (31:2)
29: 
30: import {
31:   cookingTimes,
      ^
32:   cup1
33: } from './files.js'
Error: 'cookingTimes' is not exported by src/files.js
```

**Comment by atherdon** [comment]
Ok, you changed from cookingTimes to cooking, but did you change it at other files?
because we still have this error log(index.js):
```
src/index.js (31:2)
29: 
30: import {
31:   cookingTimes,
      ^
32:   cup1
33: } from './files.js'
Error: 'cookingTimes' is not exported by src/files.js
```

**Comment by vadim9999** [comment]
@elnur004 How it's going with this PR?

**Comment by elnur004** [comment]
@vadim9999 may be i couldn't understand this task properly, may you explain again to me please, how to do that?

**Comment by vadim9999** [comment]
> Ok, you changed from cookingTimes to cooking, but did you change it at other files?
> because we still have this error log(index.js):
> 
> ```
> src/index.js (31:2)
> 29: 
> 30: import {
> 31:   cookingTimes,
>       ^
> 32:   cup1
> 33: } from './files.js'
> Error: 'cookingTimes' is not exported by src/files.js
> ```

@elnur004 have you done this?

**Comment by vadim9999** [comment]
@elnur004 your task was to create loops for two files in generator/play/play.js right? 
The first step connect filesObject.js in play.js. 
The second step just output variable that you have imported in play.js by console.log. It's should display something like this
```
cup1:
[
   [ { name: 'cup',
       americanStandart: '16 tablespoons',
       americanStandartOunces: '8 ounces',
       volume: '240 milliliters',
       weight: '225 grams,  1/2 pound' } ],
  halfCup:
   [ { name: 'cup1_2',
       americanStandart: '8 tablespoons',
       americanStandartOunces: '4 ounces',
       volume: '120 milliliters',
       weight: '113.4 grams, 1/4 pound' } ],

]
```
in result you should something get like this
```
const static = require("../../filesObjects")
console.log(static);
```

**Comment by vadim9999** [comment]
@elnur004 what is the progress with this PR? Are you stuck? Do you need help?

**Comment by vadim9999** [comment]
https://github.com/GroceriStar/sd/issues/236

**Comment by elnur004** [comment]
@vadim9999 i have created play folder and file also loops for two files.
and this file is situated in the generator folder

**Comment by vadim9999** [comment]
@elnur004 am I right we can close this PR?

**Comment by elnur004** [comment]
yes

**Pull request closed without merging**
