### PR TITLE
upd

### PR DESCRIPTION
**Pull request by elnur004**
## Proposed changes

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request.
If it fixes a bug or resolves a feature request, be sure to link to that issue.

## Types of changes

What types of changes does your code introduce to static food data?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] refactor
- [ ] documentation
- [ ] other

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

Are tests included?
- [ ] yes (*bugfixes and features will not be merged without tests*)
- [ ] no

Breaking Changes?
- [ ] yes (*breaking changes will not be merged unless absolutely necessary*)
- [ ] no

List any relevant issue numbers:

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by atherdon** [comment]
1) can you tell me what this changes is about - i don't recall them.
2) we have an error here. error log is:
```
 /home/travis/build/GroceriStar/sd/tests/cookingTimes.test.js:196:5: 'ecpect' is not defined.
  /home/travis/build/GroceriStar/sd/tests/cup1_8.test.js:6:9: Identifier 'cup1_8' is not in camel case.
  /home/travis/build/GroceriStar/sd/tests/cup3_4.test.js:6:9: Identifier 'cup3_4' is not in camel case.
```
3) will check it in details soon

**Comment by elnur004** [comment]
this changes about test jest json schema.
btw i can't test the files via my editor, there show up some kind of errors

**Comment by atherdon** [comment]
i think it's just a simple mistake, that you've made
```
/home/travis/build/GroceriStar/sd/tests/cookingTimes.test.js:196:5: 'ecpect' is not defined.
```

**Comment by elnur004** [comment]
should to test all objects in cookingTimes as i did?

**Comment by atherdon** [comment]
i think it's not related to your latest changes. read an error. find a line number and find out what is wrong

**Comment by atherdon** [comment]
tests will pass right now i assume

**Comment by atherdon** [comment]
check this error log:
```
40 |       required: ['name', 'boil', 'microvave', 'steam', 'roast']
      41 |     }
    > 42 |     expect({ name: 'frenchBeans', boil: '6 - 10 mins', microwave: '4 - 6 mins', steam: '8 - 12 mins', roast: '25 - 30 mins' }).toMatchSchema(schema)
         |                                                                                                                                ^
      43 |   })
      44 | })
```

**Comment by atherdon** [comment]
you can actually check them by yourself by clicking on red X -> Details

**Comment by elnur004** [comment]
ok. i got

**Comment by atherdon** [comment]
check build log

**Pull request merged**
