### PR TITLE
JSON validation

### PR DESCRIPTION
**Pull request by wahaj-47**

### CODE REVIEW

**Comment by atherdon** [comment]
ok, looks valid. what do you think about how we can improve this code?

**Comment by wahaj-47** [comment]
What does the path.resolve method do ?

**Comment by atherdon** [comment]
it's just a es5 nodejs style of getting absolute path. So it will work on
any type of OS systems, like unix, win, mac...
https://nodejs.org/docs/latest/api/path.html#path_path_resolve_paths

**Comment by wahaj-47** [comment]
Do we really need to type in the whole path every time ?

**Comment by atherdon** [comment]
it depends. what task are you reffering?

**Comment by wahaj-47** [comment]
You wanted to make improvements to this code.

**Comment by atherdon** [comment]
We just finished some changes with another intern, so you'll need to sync
your fork.
yeah, this file looks long, and i think we're a lot of repeatable stuff. My
goal is to reduce lines of code - how we can do this? but please sync first

>

**Comment by atherdon** [comment]
#53

>

**Comment by wahaj-47** [comment]
Synced my fork.

**Comment by wahaj-47** [comment]
We could use this to loop through all the files and store their path in an array https://github.com/paulmillr/readdirp

The only problem is we're going to loop through all the files. Maybe we can filter them out somehow.

**Comment by atherdon** [comment]
as we have files.js - similar to logic that we have in fetch - we can also
export an array of that files too.
will look like export {
file1, file2,file3,
array:[file1,file2,file3]
}
in this case our prev functionality will work, and you'll receive an array
- that you can use in loop.
Not sure if we'll need that lib with this approach

>

**Comment by wahaj-47** [comment]
I don't think the jsonlint.config.js is doing anything as of now.

**Comment by wahaj-47** [comment]
Getting this for each shell.exec

**Comment by wahaj-47** [comment]
Why are there two files.js 
One inside the src folder and another outside.

**Comment by atherdon** [comment]
1) are they similar? give me a full link to files - i'll take a look
2) how did you run a script, that uses jsonlint?

**Comment by wahaj-47** [comment]
1. No they're not similar.
    files.js: https://github.com/GroceriStar/sd/blob/master/files.js
    src/files.js: https://github.com/GroceriStar/sd/blob/master/src/files.js

2. npm run jsonlint

**Comment by atherdon** [comment]
1) I will take a look. the main reason for having these 2 files is:
a) file, that uses es5 style - for including files for jsonlint check - it's our dev file. we didn't push it on npm. it's only for us, in order to understand if each of our files is good. 
b) file that has es6 style, and connects to our main file - index.js - it uses import instead of requiring and we have a tool with name `babel` - that made our code accessible for both es5 & es6. so the logic of this files is similar but syntax is different.  it's also not finished, because our other intern just going through "intro" phase, so we're making small steps. We may need to change this logic = you can create a separated task, where we can discuss different ways how to resolve it.
2) good

**Comment by atherdon** [comment]
i have this idea - maybe you can create another separated file, but instead of using es5 style, connect one of our json files and run `shelljs exec`? can you do it?

**Comment by wahaj-47** [comment]
I don't quite understand what you mean

**Comment by wahaj-47** [comment]
This file.js: https://github.com/GroceriStar/sd/blob/master/files.js

**Comment by wahaj-47** [comment]
```
import {
    allergies
} from './src/files'
```

If I use this in jsonlint.config.js I get 

import {
            ^

SyntaxError: Unexpected token {

**Comment by atherdon** [comment]
at `jsonlint` try to use require. because `jsonlint` file has es5 syntax.
this is why we have this "situation"

**Pull request merged**
