### PR TITLE
created play.js

### PR DESCRIPTION
**Pull request by elnur004**

### CODE REVIEW

**Comment by atherdon** [comment]
@elnur004 can you mention to what task this PR related too?

**Comment by vadim9999** [comment]
this task for issue https://github.com/GroceriStar/sd/issues/236 I think it's very hard to do it Elnur

**Comment by atherdon** [comment]
lets change a plan then. or add more details into task description.
so it's more like our problem Vadim and Arthur :) not Elnur fault.
Do you think we can extend that task and make an explanation better with step by step plan

**Comment by vadim9999** [comment]
ok

**Comment by atherdon** [comment]
> ok

please put everything from A to Z into task description and we'll restart everything if you think that we're doing something not correctly

**Comment by elnur004** [comment]
@atherdon @vadim9999 Hi,
actually, that task was a little bit tough for me. maybe this was a result of lacking my practice. but i really so much wanted to solve that task.
if there will be any task for me, i'm very enthusiastic to do that.

**Comment by vadim9999** [comment]
@elnur004 No problem, I will add more details related to this task

**Comment by vadim9999** [comment]
https://github.com/GroceriStar/sd/issues/236

**Comment by atherdon** [comment]
> ctually, that task was a little bit tough for me. maybe this was a result of lacking my practice.

Don't worry at all. we just growing a team drastically and updating our coding workflow, so i assume soon all will become clear and easier to work on. at least i'm pause my coding and focusing on team management

**Comment by atherdon** [comment]
Btw Elnur, by watching(stalking) on your commits i have feeling that we need to extend your skills at git/github a bit. And it maybe will make everything a bit easier Tell me what do you think. I have a big pile of data about git. i store it here: https://github.com/ChickenKyiv/awesome-git-article

**Comment by elnur004** [comment]
yes, Arthur. You right. i started to curious about github recently. for that reason maybe i don't know much features about git/github.

**Comment by atherdon** [comment]
github is a great place. i'm feeling here in save with my code. ok, i'll need sometime and i'll be back with plan about how to extend your git skills - btw, nice progress so far!

**Comment by atherdon** [comment]
@elnur004 did we came to a solution here? was busy and not sure what we have here

**Comment by elnur004** [comment]
@atherdon i've tried to do. firs i've cloned all repo to my comp. then in generator folder created play folder and in play folder created a play.js file. but when i write code and try to test it that message shows up: Error: Cannot find module '/Users/elnur/Desktop/sd/play.js'.
btw i imported the `filesObjects` like this `const arr = require('../../filesObjects')`

**Comment by elnur004** [comment]
can you help me how to resolve this problem, please?

**Comment by atherdon** [comment]
Yes, sure. But as Vadim is our Lead here - we'll have a second way to do it.
Can you make some quick changes at
https://github.com/GroceriStar/groceristar-fetch/blob/master/src/projects/UnitConvertion/files.js
connect
all files, that you created and export them as we did with
measurementsystems file?

**Comment by atherdon** [comment]
next our quick task will be to add tests for those files: https://github.com/GroceriStar/groceristar-fetch/blob/master/src/projects/UnitConvertion/files.test.js

**Comment by atherdon** [comment]
Our next step will be:
at this line, https://github.com/GroceriStar/sd/blob/master/src/index.js#L30,
grab any 2 your files and create 2 loops(map, for or anyother) what will iterate with our arrays.

**Pull request closed without merging**
