### PR TITLE
update

### PR DESCRIPTION
**Pull request by elnur004**
## Proposed changes

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request.
If it fixes a bug or resolves a feature request, be sure to link to that issue.

## Types of changes

What types of changes does your code introduce to static food data?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] refactor
- [ ] documentation
- [ ] other

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

Are tests included?
- [ ] yes (*bugfixes and features will not be merged without tests*)
- [ ] no

Breaking Changes?
- [ ] yes (*breaking changes will not be merged unless absolutely necessary*)
- [ ] no

List any relevant issue numbers:

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by atherdon** [comment]
should i close other PRs that you open before?

**Comment by elnur004** [comment]
yes

**Comment by elnur004** [comment]
@atherdon is that true way to export default files within curly braces {...}?

**Comment by atherdon** [comment]
check this article: https://medium.com/@etherealm/named-export-vs-default-export-in-es6-affb483a0910

**Comment by elnur004** [comment]
also, you said when testing the file there was an error with exporting files.
i couldn't understand why that happened?

**Comment by atherdon** [comment]
i don't remember that - can you point directly to my message.

btw, with your changes i see another issue - right now we exporting only 2
of files, that you created before - cu1, cookingTimes. but how we should
handle your other files?

>

**Comment by elnur004** [comment]
need me to create loops for other files?

**Comment by elnur004** [comment]
> we have another small issue with that variable.
> this is a log:
> 
> ```
> [!] Error: 'cookingTimes' is not exported by src/files.js
> https://rollupjs.org/guide/en#error-name-is-not-exported-by-module-
> src/index.js (31:2)
> 29: 
> 30: import {
> 31:   cookingTimes,
>       ^
> 32:   cup1
> 33: } from './files.js'
> Error: 'cookingTimes' is not exported by src/files.js
> ```

**Comment by elnur004** [comment]
here

**Comment by atherdon** [comment]
got it - thanks!
i think the major problem here was: you imported data from `files` into
object `files`
and inside of this object you have a field, that point to cookingTimes
directly. but as you didn't `destroy` your object - this is two different
variables:
`cookingTimes` and `files.cookingTimes`

**Comment by atherdon** [comment]
actually - we still have a similar issue:
```
src/index.js (27:2)
25:   dbIngredients,
26: 
27:   cookingTimes,
      ^
28:   cup1
Error: 'cookingTimes' is not exported by src/files.js
```

**Comment by atherdon** [comment]
i think we need to check if this file exists and if we import it correctly to files.js looks like something wrong and we cannot figure out why :)

**Comment by elnur004** [comment]
@atherdon the file exists in the data folder and the importing paths are correct in files.js
 but i still can't understand what is the problem.
would this issue relate only to cookingTimes variable or other variables as well?

**Comment by atherdon** [comment]
i'm not sure, but you can find it out - just comment cooking times at export {...} and if next variable cup will generate a same error - it will be our answer. Also - you can see at "merge block" a red line - if you click on details link - you'll be able to see a similar error log that i send to you

**Comment by atherdon** [comment]
Still, as this error tell us that problem at files.js - we should focus on that file. because it's our source of bug right now

**Comment by elnur004** [comment]
there is the same issue with another variable as well.

**Comment by elnur004** [comment]
@atherdon i glanced at files.js and think paths are correct.
but i couldn't determine how to fix a problem? do you have any recommendation for me?

**Comment by atherdon** [comment]
will take a look right now. can you check another task where i mention you while i'm checking it?

**Comment by vadim9999** [comment]
Is this still alive?

**Comment by atherdon** [comment]
i don't know i maybe we need to close this PR. because we made a lot of changes from time this PR was opened

**Comment by vadim9999** [comment]
ok close it

**Pull request closed without merging**
