### PR TITLE
MeasurementSystem generated

### PR DESCRIPTION
**Pull request by wahaj-47**

### CODE REVIEW

**Comment by wahaj-47** [comment]
@atherdon Check this out.

**Comment by atherdon** [comment]
Vadim will review your PR. 
btw, quick checklist: files are exported at index.js, test were generated, jsonlint passing fine?

**Comment by vadim9999** [comment]
@atherdon Files measurementSystem and measurementUnits wasn't imported. 

>test were generated

What do you mean generated tests? Create it by hand or automitically? 
I have not seen any tests in this pull request

>jsonlint passing fine?

to run npm run jsonlint?

**Comment by vadim9999** [comment]
@wahaj-47 Please add in files.js export of this files measurementSystem and measurementUnits

**Comment by vadim9999** [comment]
@wahaj-47 Also can you add export file in files.js from folder MeasurementSystem and MeasurementUnits(that was generated by generator)

**Comment by vadim9999** [comment]
@wahaj-47 have you created tests on files that was generated? If no, please can you create it. tests are in src/data/__tests__  
it's should be the same structure as other tests.
After that can you try to run this command to know that all files output
``` 
npm run jsonlint
```

**Comment by vadim9999** [comment]
@wahaj-47 please can you add tests for json that located in folders MeasurementSystem and MeasurementUnits

**Pull request merged**
