### PR TITLE
test for getFileInfo

### PR DESCRIPTION
**Pull request by uniyalprashant9**
#424 
Tests for getFileInfo

### CODE REVIEW

**Comment by uniyalprashant9** [comment]
It needs an absloute path instead of relative path.

**Comment by uniyalprashant9** [comment]
@atherdon  I am stuck at finding the absolute path :(
Module and test are in different folders so the relative path will not work when I send it as a parameter.

**Comment by atherdon** [comment]
hmm, don't worry- it;s a common problem. why not compare it with other tests? did you tried this way?

**Comment by atherdon** [comment]
i actually think that this is a perfect way to show of how important tests and documentation is. because if you - as creator of this method - cannot deal with it - then something is not ok, right?

**Comment by atherdon** [comment]
check this and tell me what i should do - try to help you or wait while you will figure it out on your own.

check #545 

what i will do if i was you - redo that method few times. usually it helps to understand the problem better

**Comment by atherdon** [comment]
it must work with ```./sample``` or ```../tests/sample``` it's definately something not ok with code

**Comment by uniyalprashant9** [comment]
Screenshot (2)

It's working on my laptop.

**Comment by atherdon** [comment]
hmm, then google why it can be broken - because travis ci always keeping our back save. this is why we need it - in order to test for different cases and set ups

**Comment by atherdon** [comment]
still will advice to redo that method.

**Comment by uniyalprashant9** [comment]
yes I am checking that.

**Comment by atherdon** [comment]
ok, can you sync your fork with our master - because i see some conflicts?
https://github.com/ChickenKyiv/awesome-git-article#keeping-a-fork-up-to-date

**Comment by uniyalprashant9** [comment]
something is messed up I will pull request again

**Pull request closed without merging**
