### PR TITLE
updated index in src

### PR DESCRIPTION
**Pull request by uniyalprashant9**
The third pull request, earlier 2  pull requests were messed up.

### CODE REVIEW

**Comment by atherdon** [comment]
#424

**Comment by uniyalprashant9** [comment]
oh, I will merge both codes and export both objects ...which one required can be used then.

**Comment by atherdon** [comment]
perfect! please also sync your fork with latest changes that was made byother team members

**Comment by uniyalprashant9** [comment]
I am this error when I tried to run index.js that is already in our repo.

import statement have error

image

**Comment by atherdon** [comment]
can you submit your code changes - because i cannot see without code

**Pull request closed without merging**
